#!/usr/bin/env bash
# Redirects /redirect_me
sudo apt-get update;
sudo apt-get -y install nginx;
newString="rewrite ^\/redirect_me\/ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
myFile="/etc/nginx/sites-available/default"
sudo sed -i "26i $newString" $myFile;
sudo service nginx start;
