#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
newString="error_page 404 /custom_404.html;\\n location = /custom_404.html {\\n root /usr/share/nginx/html;\\n internal;\\n}"
myMatch="#error_page 404 /404.html;"
myFile="/etc/nginx/sites-available/default"
udo sed -i "s$myMatch $newString" $myFile;
service nginx start
