#!/usr/bin/env bash
# Configures a HTTP Header
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "33i\		add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
