#!/usr/bin/env bash
# Printing messages for given num
i=1
while [ $i -le 23 ]
do
    case "$i" in
        5)
            echo "bad luck from China"
            ;;
        10)
            echo "bad luck from Japan"
            ;;
        18)
            echo "bad luck from Italy"
            ;;
        $i) echo $i
            ;;
    esac
    i=$(( i+1 ))
done
