#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
i=1
while [ $i -le 100 ]
do
    if [ $((i%15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i%5)) -eq  0 ]
    then
        echo "Buzz"
    elif [ $((i%3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo $i
    fi
    i=$(( i+1 ))
done
