#!/usr/bin/env bash
# Sets a configuration file
Host *
   ForwardAgent no
   ForwardX11 no
   ForwardX11Trusted yes
   RhostsRSAAuthentication no
   RSAAuthentication yes
   PasswordAuthentication yes
