#!/usr/bin/env bash
i=0
while [ $i -le 12 ]
do
    j=0
    while [ $j -le 59 ]
    do
        if [ $j -eq 0 ]
        then
            echo "Hour:" $i
        else
            echo $j
        fi
        j=$(( j+1 ))
    done
    i=$(( i+1 ))
done
